#!/bin/bash
echo "usage: $0 run|valgrind|gdb|clean [options]"
exdir=$(pwd)
#LIBS=${exdir}/../..:${ESP8266ARDUINO}/libraries/Hash
LIBS=${exdir}/../..
cd ${ESP8266ARDUINO}/tests/host
cmd="$1"

[ "$cmd" = "" ] && exit 1

if [ "$cmd" = clean ]; then
    make clean
else
    [ "$cmd" = run ] && cmd=""
    shift
    set -ex
    make ULIBDIRS=$LIBS FORCE32=0 V=1 ${exdir}/Simple
    $cmd ./bin/Simple/Simple "$@"
fi

stty sane
