#!/bin/bash

set -ex

# http://www.webdav.org/neon/litmus/

v=litmus-0.13

if [ ! -d ${v} ]; then
    wget http://www.webdav.org/neon/litmus/${v}.tar.gz
    tar xvfz ${v}.tar.gz
    cd ${v}
    ./configure
    make
    cd ..
fi

cd ${v}
for t in basic copymove props locks http; do
    ./${t} http://ESPWebDav.local:9080/ || true
done